# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-31 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('real_team', models.CharField(max_length=3)),
                ('cost', models.IntegerField()),
                ('auction_value', models.IntegerField(null=True)),
                ('role', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('budget', models.IntegerField()),
                ('max_trades', models.IntegerField()),
                ('max_goalkeepers', models.IntegerField()),
                ('max_defenders', models.IntegerField()),
                ('max_midfielders', models.IntegerField()),
                ('max_forwards', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Team'),
        ),
    ]
