import wx


OK = wx.OK | wx.ICON_EXCLAMATION
ACV = wx.ALIGN_CENTER_VERTICAL
ACH = wx.ALIGN_CENTER_HORIZONTAL | wx.ALL
YN = wx.YES_NO | wx.ICON_WARNING
DD = wx.CB_DROPDOWN
HS = wx.LB_HSCROLL
STYLE_PB = wx.PD_AUTO_HIDE | wx.PD_ELAPSED_TIME | wx.PD_REMAINING_TIME
ACVE = wx.ALIGN_CENTER_HORIZONTAL | wx.EXPAND
